# Generated by Django 5.0.7 on 2024-09-20 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_pizzauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drinks', models.ManyToManyField(blank=True, to='models.drinks')),
                ('pizzas', models.ManyToManyField(blank=True, to='models.pizza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.pizzauser')),
            ],
        ),
    ]
