# Generated by Django 5.0.7 on 2024-09-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
    ]
