# Generated by Django 5.0.7 on 2024-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
