# Generated by Django 5.0.7 on 2024-10-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_drinks_quantity_pizza_quantity_alter_basket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='quantity',
        ),
    ]
